language: node_js
node_js:
  - "5.10.0"
  - "7.6.0"
env:
  CODECLIMATE_REPO_TOKEN: 008966c615a64641f96bc3c02719ffc6f80266de0c4b2ebe5d6131ca302ebea8
install:
  - npm install
script:
  - npm run coverage
after_script:
  - npm install -g codecov
  - codecov
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
